appenders:
  stdout:
    kind: console
    encoder:
      pattern: '{d(%+)} [{f}:{L}] {h({l})} {M}:{m}{n}'
    filters:
      - kind: threshold
        level: info
  rollingfile:
    kind: rolling_file
    path: '/tmp/armIps_log/app.log'
    encoder:
      pattern: '[{d(%Y-%m-%dT%H:%M:%S%.6f)} {h({l}):<5.5} {M}] {m}{n}'
    policy:
      trigger:
        kind: size
        limit: 100 mb
      roller:
        kind: fixed_window
        pattern: '/tmp/armIps_log/app-{}.log'
        base: 0
        count: 10
root:
  level: info
  appenders:
    - stdout
    - rollingfile
