name: 'publish'
on:
  push:
    branches:
      - main

jobs:
  publishtauri:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - macos-latest
          - ubuntu-20.04
          - ubuntu-20.04-arm64
          - windows-latest

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Add ARM64 target (Linux)
        if: matrix.platform == 'ubuntu-20.04-arm64'
        run: rustup target add aarch64-unknown-linux-gnu

      - name: Install system dependencies (Linux ARM64)
        if: matrix.platform == 'ubuntu-20.04-arm64'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu libc6-dev-arm64-cross

      - name: Install frontend dependencies
        run: pnpm install

      - uses: tauri-apps/tauri-action@v0
        id: tauri
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: Arm-Ips-v__VERSION__
          releaseName: 'Arm Ips v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: false
          prerelease: false
          includeUpdaterJson: true
          updaterJsonPreferNsis: true

      - name: List output files
        run: ls -alh src-tauri/target
