name: 'publish'
on:
  push:
    branches:
      - main

jobs:
  publishtauri:
    strategy:
      matrix:
        platform:
          - ubuntu-20.04
          - windows-latest
          - linux-arm64
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install ARM64 toolchain
        if: matrix.platform == 'linux-arm64'
        run: |
          rustup target add aarch64-unknown-linux-gnu
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu libc6-dev-arm64-cross

      - name: Install system dependencies (Linux ARM64)
        if: matrix.platform == 'linux-arm64'
        run: |
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: Install dependencies
        run: pnpm install

      - name: Build Tauri for ARM64
        if: matrix.platform == 'linux-arm64'
        run: |
          cargo tauri build --target aarch64-unknown-linux-gnu

      - name: Verify build output
        run: |
          ls -alh src-tauri/target/aarch64-unknown-linux-gnu/release/bundle/

      - uses: tauri-apps/tauri-action@v0
        id: tauri
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          includeRelease: false # Disable internal build to use manually built files
